rbp_encode_list: [
    "AGGF1",
    "AKAP1",
    "AQR",
    "BUD13",
    "CSTF2T",
    "DDX3X",
    "DDX52",
    "DDX55",
    "DDX6",
    "DGCR8",
    "DHX30",
    "DROSHA",
    "EFTUD2",
    "EXOSC5",
    "FAM120A",
    "FASTKD2",
    "FTO",
    "FUS",
    "FXR2",
    "GRWD1",
    "GTF2F1",
    "HLTF",
    "HNRNPA1",
    "HNRNPC",
    "HNRNPK",
    "HNRNPL",
    "HNRNPM",
    "HNRNPU",
    "HNRNPUL1",
    "IGF2BP1",
    "ILF3",
    "KHSRP",
    "LARP4",
    "LARP7",
    "LIN28B",
    "LSM11",
    "MATR3",
    "NCBP2",
    "NOLC1",
    "PCBP1",
    "PRPF8",
    "PTBP1",
    "QKI",
    "RBFOX2",
    "RBM15",
    "RBM22",
    "RPS3",
    "SAFB",
    "SDAD1",
    "SF3B4",
    "SLTM",
    "SMNDC1",
    "SND1",
    "SRSF1",
    "SRSF7",
    "SSB",
    "SUPV3L1",
    "TAF15",
    "TBRG4",
    "TIA1",
    "TRA2A",
    "TROVE2",
    "U2AF1",
    "U2AF2",
    "UCHL5",
    "UPF1",
    "UTP18",
    "WDR43",
    "XRCC6",
    "XRN2",
    "YBX3",
    "ZC3H11A",
    "ZNF800",
]